version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/crud
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: chanyoup1@
    depends_on:
      mysql:
        condition: service_healthy  # 컨테이너가 준비되었는지 확인


  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: chanyoup1@
      MYSQL_DATABASE: crud
#      MYSQL_USER: root
#      MYSQL_PASSWORD: chanyoup1@
    ports:
      - "3306:3306"
    volumes:
      - db_mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  db_mysql:
